url: "{% if prometheus_node_exporter_url is not defined %}{% if prometheus_node_exporter_version | version_compare('0.13.0', '>=') %}https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/{{ prometheus_node_exporter_release_name }}.tar.gz{% else %}https://github.com/prometheus/node_exporter/releases/download/{{ prometheus_node_exporter_version }}/{{ prometheus_node_exporter_release_name }}.tar.gz{% endif %}{% else %}{{ prometheus_node_exporter_url }}{% endif %}"
prometheus_exporters_common_user:   prometheus
prometheus_exporters_common_group:  prometheus

prometheus_exporters_common_root_dir: /opt/prometheus/exporters
prometheus_exporters_common_dist_dir: "{{ prometheus_exporters_common_root_dir }}/dist"
prometheus_exporters_common_log_dir:  /var/log/prometheus
prometheus_exporters_common_conf_dir: /etc/prometheus/exporters
